server:
  servlet:
    context-path: /api

realworld:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 3000000

spring:
  data:
      mongodb:
        uri: mongodb://127.0.0.1/realworldjava3
#        host: localhost
#        port: 27017
        database: realworldjava3
  jpa:
    hibernate:
      ddl-auto: update

